saveExact: true
dedupePeers: true
minimumReleaseAge: 10080 # 1 week
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 40320 # 4 weeks
trustPolicyExcludePrune: true
