#!/usr/bin/env bash
# Prepares a release: consumes the pending changesets, formats and commits the result, and creates
# the release tag. Pushing the tag is left to the caller, because it triggers the publication to the
# Gradle Plugin Portal.
set -euo pipefail

cd "$(dirname "$0")/.."

fail() {
  echo "error: $*" >&2
  exit 1
}

if [ -n "$(git status --porcelain)" ]; then
  fail "the working tree is not clean"
fi

if ! compgen -G ".changeset/*.md" > /dev/null ||
  [ -z "$(find .changeset -maxdepth 1 -name '*.md' ! -name 'README.md' -print -quit)" ]; then
  fail "no changesets to release; run 'pnpm changeset add' first"
fi

pnpm changeset version

version="$(pnpm pkg get version | tr -d '"')"
[ -n "$version" ] || fail "could not read the version from package.json"

tag="v$version"
if git rev-parse -q --verify "refs/tags/$tag" > /dev/null; then
  fail "the tag $tag already exists"
fi

# The changelog is generated by changesets and formatted by Spotless, which enforces its format in
# the build.
./gradlew spotlessApply

git add -A
git commit -m "chore: Version plugin"
git tag "$tag"

echo
echo "Prepared $tag. Push it to publish the release:"
echo "  git push --follow-tags origin $(git rev-parse --abbrev-ref HEAD)"
